@startuml
left to right direction
skinparam packageStyle rectangle

actor "Usuário" as U
actor "Cliente" as C
actor "Administrador" as A

' Herança de Atores
C --|> U
A --|> U

package "Módulo: Usuário" {
    usecase "RF01 - Criar Perfil de Usuário" as RF01
    usecase "RF02 - Realizar Autenticação" as RF02
    usecase "RF07 - Visualizar Perfil" as RF07
    usecase "RF08 - Alterar Perfil" as RF08
    usecase "RF09 - Desativar/Ativar Perfil" as RF09
    usecase "RF10 - Exclusão de Perfil" as RF10

    usecase "Realizar Autenticação \n (Como Cliente)" as RF02C
    usecase "Realizar Autenticação \n (Como Administrador)" as RF02A
}

package "Módulo: Conta (Cliente) & Cartões" as cc {
    usecase "RF03 - Abrir e Encerrar Contas" as RF03
    usecase "RF04 - Visualizar Lista de Contas" as RF04
    usecase "RF05 - Escolher e Alternar Contas" as RF05
    usecase "RF06 - Visualizar Dados da Conta" as RF06
    
    usecase "RF11 - Criar e Excluir Cartões" as RF11
    usecase "RF12 - Visualizar Dados do Cartão" as RF12
    usecase "RF13 - Bloquear e Desbloquear Cartão" as RF13
    usecase "RF14 - Visualizar e Ajustar Limite" as RF14
    
    usecase "RF15 - Realizar Transações" as RF15
    usecase "RF16 - Visualização de Extratos" as RF16
}

package "Módulo: Investimento" as inv{
    usecase "RF17 - Realizar Investimentos" as RF17
    usecase "RF18 - Resgate de Investimentos" as RF18
    usecase "RF19 - Visualização de Investimentos" as RF19
}

package "Módulo: Administrador" as aa {
    usecase "RF20 - Gerenciamento de Clientes" as RF20
    usecase "RF21 - Gerenciamento de Contas" as RF21
    usecase "RF22 - Gerar Relatório Geral" as RF22
}

package "Módulo: Regras de Tipos de Conta" {
    usecase "RF23 - Regras Conta Poupança" as RF23
    usecase "RF24 - Regras Conta Investimento" as RF24
    usecase "RF25 - Regras Conta Kids" as RF25
}

' Associações do Usuário (Geral)
U -- RF01
RF01 <.. RF02 : <<extend>>
U -- RF07
U -- RF08
U -- RF09
U -- RF10

' Associações do Cliente
' Associações do Administrador
A -- RF14 : "Avaliar Solicitação"

' Relacionamentos de Extensão para Regras de Negócio de Tipos de Conta
RF15 ..> RF23 : <<extend>>
RF15 ..> RF24 : <<extend>>
RF15 ..> RF25 : <<extend>>

RF02 <|-right- RF02C 
RF02 <|-left- RF02A 

A -left- RF02A 
C -- RF02C

RF02C -up-> cc
RF02C -up-> inv
RF02A -right-> aa

@enduml